---
title: "Spike Trains : Krebs"
author: "Karishma Carter Johnson"
date: "5/5/2019"
output: html_document
---

# Time 100 : 1000
```{r echo = FALSE,eval = TRUE, message = FALSE}
library(R.matlab) 

ephysroot = 'C:/Users/karis/Desktop/'; # path of the data set 
mstr = 'Krebs'; # mouse names
### Load saved data:
exp_data<- readMat(paste(ephysroot,mstr,'_reduced.mat',sep=''));
# check out data structure
str(exp_data)

brain_regions= ls(exp_data)[-c(1:3)]; 
n_time= dim(exp_data$faceSVD)[2];
n_sv = dim(exp_data$faceSVD)[1];


library(ggplot2)

plot_list = list()
for(i_region in 1:9) {
      time_range = c(100, 1000); # indices of time frame
      
      ### Extract the spike train for this region
      spikes_this_region = exp_data[[brain_regions[i_region]]]
      
      ### Visualize the spike train 
      n_neurons = dim(spikes_this_region)[1]; 
      p = plot(x=0,y=0,pch=16,col="white",type="l",lwd=3,ylim=c(0,n_neurons),
               xlim=time_range,cex.lab=1,cex.main=1,ylab='Neuron',xlab='Time frame',
               main=paste0("Spike Train Region ", i_region, " Time ", time_range[1], 
                " to ", time_range[2]))
               #yaxt='n',xaxt='n',
      
      for(i_neuron in 1:n_neurons){
        spk_times =which(spikes_this_region[i_neuron,time_range[1]:time_range[2]]>0);
        if (length(spk_times)>0){
          points(y=rep(i_neuron,length(spk_times)),x=spk_times+time_range[1]-1,col="#000000",pch='.',cex=2)
        }
      }
      
      plot_list[[i_region]] = p

}
```

# Time 1000:2000

```{r echo = FALSE, eval = TRUE, message = FALSE}
plot_list = list()
for(i_region in 1:9) {
      time_range = c(1000, 2000); # indices of time frame
      
      ### Extract the spike train for this region
      spikes_this_region = exp_data[[brain_regions[i_region]]]
      
      ### Visualize the spike train 
      n_neurons = dim(spikes_this_region)[1]; 
      p = plot(x=0,y=0,pch=16,col="white",type="l",lwd=3,ylim=c(0,n_neurons),
               xlim=time_range,cex.lab=1,cex.main=1,ylab='Neuron',xlab='Time frame',
               main=paste0("Spike Train Region ", i_region, " Time ", time_range[1], 
                " to ", time_range[2]))
               #yaxt='n',xaxt='n',
      
      for(i_neuron in 1:n_neurons){
        spk_times =which(spikes_this_region[i_neuron,time_range[1]:time_range[2]]>0);
        if (length(spk_times)>0){
          points(y=rep(i_neuron,length(spk_times)),x=spk_times+time_range[1]-1,col="#000000",pch='.',cex=2)
        }
      }
      
      plot_list[[i_region]] = p

}
```
